### ISSUE TITLE
Adding libraries to chroot that are not available directly in apt

### ISSUE THREAD

**Issue by Gravlok** [tttapa/RPi-Cross-Cpp-Development#1]
Hi!
I want to include within my project a ZMQ messaging library. There is a base library available (libzmq3-dev) in apt, but it requires a wrapper around it (cppzmq - https://github.com/zeromq/cppzmq). How can I build and install this library in the chroot?

**Comment by tttapa** [comment]
You can follow the CMake instructions here: https://tttapa.github.io/Pages/Raspberry-Pi/C++-Development-RPiOS/Building-example-project.html#manual-build  
They should apply to pretty much any CMake project, not just the example project, just make sure you use the path to the right toolchain file.

To install the project into the chroot, you can use `cmake --install build --prefix /var/lib/schroot/chroots/rpizero-buster-armhf/usr/local` (changing the name of the chroot as appropriate, probably requires sudo).
